# Generated by Django 5.2.7 on 2025-11-01 18:49

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('entities', '0001_initial'),
        ('widgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('removed', 'Removed'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='topics.topic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('entities', models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEntity', to='entities.entity')),
                ('events', models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEvent', to='agenda.event')),
                ('related_topics', models.ManyToManyField(blank=True, related_name='related_to_topics', through='topics.RelatedTopic', to='topics.topic')),
            ],
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='related_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_topic_links', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_related_topics', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedevent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_event_links', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedentity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entities', to='topics.topic'),
        ),
        migrations.CreateModel(
            name='TopicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.JSONField()),
                ('sources', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicDataAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('saved_insight_ids', models.JSONField(blank=True, default=list)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_analysis_requests', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_data_analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopicDataInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('insight', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sources', models.ManyToManyField(related_name='insights', to='topics.topicdata')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_insights', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('url', 'URL'), ('search', 'Search')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='topics.topicdata')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopicDataVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('chart_type', models.CharField(max_length=50)),
                ('chart_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualizations', to='topics.topicdatainsight')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_visualizations', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicDataVisualizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_visualization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_visualization_requests', to='topics.topicdatavisualization')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_visualization_requests', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_data_visualization_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('ppt', 'PowerPoint'), ('xls', 'Spreadsheet'), ('txt', 'Text'), ('other', 'Other')], default='other', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('image', models.ImageField(upload_to='topics_images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='topics_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_hero', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recap', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('content', models.JSONField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='topics.topic')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='widgets.widget')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TopicText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='finished', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('tweet_id', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField()),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='topics.topic')),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TopicWebpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Webpage',
                'verbose_name_plural': 'Webpages',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicYoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordering position within the topic's content column.")),
                ('url', models.URLField(blank=True, null=True)),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('video_published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='topics.topic')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='topic_embedding_hnsw', opclasses=['vector_l2_ops']),
        ),
        migrations.AddConstraint(
            model_name='relatedtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'related_topic'), name='unique_topic_related_topic'),
        ),
        migrations.AddConstraint(
            model_name='relatedevent',
            constraint=models.UniqueConstraint(fields=('topic', 'event'), name='unique_topic_related_event'),
        ),
        migrations.AddConstraint(
            model_name='relatedentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('topic', 'entity'), name='unique_topic_related_entity'),
        ),
        migrations.AddIndex(
            model_name='topicdocument',
            index=models.Index(fields=['topic'], name='topics_topi_topic_i_e00806_idx'),
        ),
        migrations.AddIndex(
            model_name='topicdocument',
            index=models.Index(fields=['document_type'], name='topics_topi_documen_eeb3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='topicdocument',
            index=models.Index(fields=['display_order'], name='topics_topi_display_8bcffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='topictitle',
            constraint=models.UniqueConstraint(fields=('slug', 'topic'), name='unique_topic_title_slug'),
        ),
        migrations.AddConstraint(
            model_name='topictweet',
            constraint=models.UniqueConstraint(fields=('topic', 'tweet_id'), name='unique_topic_tweet'),
        ),
        migrations.AddIndex(
            model_name='topicwebpage',
            index=models.Index(fields=['topic'], name='topics_topi_topic_i_e5a6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='topicwebpage',
            index=models.Index(fields=['created_at'], name='topics_topi_created_a10f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='topicwebpage',
            index=models.Index(fields=['display_order'], name='topics_topi_display_6d54df_idx'),
        ),
    ]
