# Generated by Django 5.2.8 on 2025-12-17 08:12

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('removed', 'Removed'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='topics.topic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('entities', models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEntity', to='entities.entity')),
                ('events', models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEvent', to='agenda.event')),
                ('related_topics', models.ManyToManyField(blank=True, related_name='related_to_topics', through='topics.RelatedTopic', to='topics.topic')),
            ],
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='related_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_topic_links', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_related_topics', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedevent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_event_links', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='relatedentity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entities', to='topics.topic'),
        ),
        migrations.CreateModel(
            name='TopicRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recap', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(db_index=True, max_length=100)),
                ('draft_display_order', models.PositiveSmallIntegerField(default=0)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_draft_deleted', models.BooleanField(default=False)),
                ('language_code', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='topics.topic')),
            ],
            options={
                'ordering': ('draft_display_order', 'published_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TopicSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('snapshot', 'Snapshot')], default='draft', max_length=20)),
                ('content', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('execution_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to='topics.topicsection')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='topicsection',
            name='draft_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_sections', to='topics.topicsectioncontent'),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='published_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sections', to='topics.topicsectioncontent'),
        ),
        migrations.CreateModel(
            name='TopicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='topics.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='topic',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='topic_embedding_hnsw', opclasses=['vector_l2_ops']),
        ),
        migrations.AddConstraint(
            model_name='relatedtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'related_topic'), name='unique_topic_related_topic'),
        ),
        migrations.AddConstraint(
            model_name='relatedevent',
            constraint=models.UniqueConstraint(fields=('topic', 'event'), name='unique_topic_related_event'),
        ),
        migrations.AddConstraint(
            model_name='relatedentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('topic', 'entity'), name='unique_topic_related_entity'),
        ),
        migrations.AddConstraint(
            model_name='topictitle',
            constraint=models.UniqueConstraint(fields=('slug', 'topic'), name='unique_topic_title_slug'),
        ),
    ]
