# Generated by Django 5.2.1 on 2025-06-17 12:49

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
