# Generated by Django 5.2.1 on 2025-09-06 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topicevent',
            name='topics_topi_topic_i_4d1d73_idx',
        ),
        migrations.RemoveField(
            model_name='topicevent',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='topicevent',
            name='rank',
        ),
        migrations.AddField(
            model_name='topicevent',
            name='significance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'High'), (3, 'Very high')], default=1),
        ),
        migrations.AddIndex(
            model_name='topicevent',
            index=models.Index(fields=['topic', 'significance'], name='topics_topi_topic_i_b044ac_idx'),
        ),
    ]
