# Generated by Django 5.2.7 on 2025-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsection',
            options={'ordering': ('display_order', 'published_at', 'id')},
        ),
        migrations.AddField(
            model_name='topicsection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='language_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='source',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20),
        ),
    ]
