# Generated by Django 5.2.6 on 2025-11-18 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topicsection',
            name='execution_state',
        ),
        migrations.RemoveField(
            model_name='topicsection',
            name='metadata',
        ),
        migrations.CreateModel(
            name='TopicSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('snapshot', 'Snapshot')], default='draft', max_length=20)),
                ('content', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('execution_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('publication_context', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to='topics.topicsection')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='topicsection',
            name='draft_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_sections', to='topics.topicsectioncontent'),
        ),
        migrations.AddField(
            model_name='topicsection',
            name='published_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sections', to='topics.topicsectioncontent'),
        ),
    ]
