# Generated by Django 5.2.7 on 2025-11-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_alter_topicsection_options_topicsection_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicsection",
            name="error_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicsection",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
