# Generated by Django 5.2.6 on 2025-11-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_remove_topicsection_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsectioncontent',
            name='publication_context',
        ),
    ]
