# Generated by Django 5.2.1 on 2025-08-23 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_entry_contents_alter_entry_options_and_more'),
        ('contents', '0002_contententry_content_entries_and_more'),
        ('topics', '0002_topiccategory_topic_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('support', 'Support'), ('counter', 'Counter'), ('context', 'Context')], default='support', max_length=20)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('rule', 'Rule')], default='user', max_length=10)),
                ('relevance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('pinned', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='topiccontent',
            name='topiccontent_embedding_hnsw',
        ),
        migrations.RenameField(
            model_name='topiccontent',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topiccontent',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='topiccontent',
            unique_together={('topic', 'content')},
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='role',
            field=models.CharField(choices=[('evidence', 'Evidence'), ('summary', 'Summary'), ('quote', 'Quote')], default='evidence', max_length=20),
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('ml', 'ML'), ('rule', 'Rule')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='relevance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='topiccontent',
            index=models.Index(fields=['topic'], name='topics_topi_topic_i_6f47f7_idx'),
        ),
        migrations.AddIndex(
            model_name='topiccontent',
            index=models.Index(fields=['content'], name='topics_topi_content_52c700_idx'),
        ),
        migrations.AddField(
            model_name='topicentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.entry'),
        ),
        migrations.AddField(
            model_name='topicentry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.TopicEntry', to='agenda.entry'),
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='embedding',
        ),
        migrations.AddIndex(
            model_name='topicentry',
            index=models.Index(fields=['topic'], name='topics_topi_topic_i_924702_idx'),
        ),
        migrations.AddIndex(
            model_name='topicentry',
            index=models.Index(fields=['entry'], name='topics_topi_entry_i_b86cae_idx'),
        ),
        migrations.AddIndex(
            model_name='topicentry',
            index=models.Index(fields=['topic', 'pinned', 'rank'], name='topics_topi_topic_i_f51112_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicentry',
            constraint=models.UniqueConstraint(fields=('topic', 'entry'), name='uniq_topic_entry'),
        ),
    ]
