# Generated by Django 5.2.1 on 2025-09-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_remove_topicevent_topics_topi_topic_i_4d1d73_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicImage',
        ),
    ]
