# Generated by Django 5.2.1 on 2025-09-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_delete_topicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topics_images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='topics_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topics.topic')),
            ],
        ),
    ]
