# Generated by Django 5.2.6 on 2025-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topicsectioncontent_publication_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsection',
            name='is_draft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
