# Generated by Django 5.2.6 on 2025-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topicimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrecap',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('error', 'Error')], default='in_progress', max_length=20),
        ),
    ]
