# Generated by Django 5.2.7 on 2025-11-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_delete_mcpserver_remove_topicdatainsight_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsection',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='topicsection',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='topicsection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='topicsection',
            name='status',
        ),
    ]
