# Generated by Django 5.2.1 on 2025-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('removed', 'Removed'), ('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
