# Generated by Django 5.2.6 on 2025-12-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topicsection_draft_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsection',
            options={'ordering': ('draft_display_order', 'published_at', 'id')},
        ),
    ]
