# Generated by Django 5.2.6 on 2025-09-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_topicrecap_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("narrative", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("finished", "Finished"),
                            ("error", "Error"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narratives",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
