# Generated by Django 5.2.1 on 2025-08-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topic_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='topic',
        ),
        migrations.CreateModel(
            name='TopicContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='contributors',
            field=models.ManyToManyField(through='topics.TopicContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='TopicCategory',
        ),
    ]
