# Generated by Django 5.2.1 on 2025-08-23 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # The ``Keyword`` model originally lived in the ``topics`` app and was later
    # extracted into its own ``keywords`` app.  In order for the foreign key
    # references below to resolve when applying migrations from a fresh
    # database, we must depend on the initial migration of the ``keywords`` app.
    # Without this dependency Django raises a ``ValueError`` claiming the
    # ``keywords`` app is not installed because the model state is missing.
    dependencies = [
        ('topics', '0006_remove_topic_categories_and_more'),
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.TopicKeyword', to='keywords.keyword'),
        ),
    ]
