# Generated by Django 5.2.1 on 2025-08-23 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # The Keyword model was originally part of the ``topics`` app and was
    # later extracted into its own ``keywords`` app. Older databases may have
    # already applied this migration before the new app existed which caused
    # Django to complain about an inconsistent migration history.  Removing the
    # explicit dependency on ``keywords`` allows those installations to run
    # ``makemigrations``/``migrate`` again without having to fake apply the
    # initial keywords migration.
    dependencies = [
        ('topics', '0006_remove_topic_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.TopicKeyword', to='keywords.keyword'),
        ),
    ]
