# Generated by Django 5.2.1 on 2025-08-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_keyword_topickeyword_keyword_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='contributors',
        ),
    ]
