# Generated by Django 5.2.6 on 2025-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topicentityrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicentityrelation',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicnarrative',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicrecap',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
