# Generated by Django 5.2.6 on 2025-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0008_topicdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicdata",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
