# Generated by Django 5.2.1 on 2025-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_remove_topic_contributors'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topicimage',
            name='topicimage_embedding_hnsw',
        ),
        migrations.RemoveField(
            model_name='topicimage',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='topicimage',
            name='image',
            field=models.ImageField(upload_to='topics_images'),
        ),
        migrations.AlterField(
            model_name='topicimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='topics_images'),
        ),
    ]
