# Generated by Django 5.2.1 on 2025-08-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_rename_entry_event'),
        ('contents', '0004_rename_contententry_contentevent_and_more'),
        ('topics', '0009_remove_topicimage_topicimage_embedding_hnsw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicEntry',
            new_name='TopicEvent',
        ),
        migrations.RemoveConstraint(
            model_name='topicevent',
            name='uniq_topic_entry',
        ),
        migrations.RemoveIndex(
            model_name='topicevent',
            name='topics_topi_entry_i_b86cae_idx',
        ),
        migrations.RenameField(
            model_name='topicevent',
            old_name='entry',
            new_name='event',
        ),
        migrations.RenameIndex(
            model_name='topicevent',
            new_name='topics_topi_topic_i_c24cda_idx',
            old_name='topics_topi_topic_i_924702_idx',
        ),
        migrations.RenameIndex(
            model_name='topicevent',
            new_name='topics_topi_topic_i_4d1d73_idx',
            old_name='topics_topi_topic_i_f51112_idx',
        ),
        migrations.AlterUniqueTogether(
            name='topiccontent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='entries',
        ),
        migrations.AddField(
            model_name='topic',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.TopicEvent', to='agenda.event'),
        ),
        migrations.AddIndex(
            model_name='topicevent',
            index=models.Index(fields=['event'], name='topics_topi_event_i_6ab48f_idx'),
        ),
        migrations.AddConstraint(
            model_name='topiccontent',
            constraint=models.UniqueConstraint(fields=('topic', 'content'), name='unique_topic_content'),
        ),
        migrations.AddConstraint(
            model_name='topicevent',
            constraint=models.UniqueConstraint(fields=('topic', 'event'), name='unique_topic_event'),
        ),
    ]
