# Generated by Django 5.2.6 on 2025-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0010_topicdatainsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicdatainsight",
            name="sources",
            field=models.ManyToManyField(
                related_name="insights", to="topics.topicdata"
            ),
        ),
    ]
