# Generated by Django 5.2.1 on 2025-08-28 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_remove_event_description'),
        ('contents', '0004_rename_contententry_contentevent_and_more'),
        ('topics', '0010_rename_topicentry_topicevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('slug', 'created_by'), name='unique_topic_title_user'),
        ),
    ]
