# Generated by Django 5.2.6 on 2025-09-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0011_topicdatainsight_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDataVisualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart_type", models.CharField(max_length=50)),
                ("chart_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visualizations",
                        to="topics.topicdatainsight",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_visualizations",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
