# Generated by Django 5.2.1 on 2025-09-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_alter_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='topics.topic'),
        ),
    ]
