# Generated by Django 5.2.6 on 2025-09-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_topicentityrelation_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrecap',
            name='error_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
