# Generated by Django 5.2.6 on 2025-09-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0014_mcpserver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopicContributor",
        ),
    ]
