# Generated by Django 5.2.6 on 2025-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0014_topicrecap_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicentityrelation",
            name="error_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicimage",
            name="error_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicimage",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topicnarrative",
            name="error_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
