# Generated by Django 5.2.6 on 2025-09-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0017_topicyoutubevideo_delete_topicmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicVimeoVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "video_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("finished", "Finished"),
                            ("error", "Error"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vimeo_videos",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
