# Generated by Django 5.2.6 on 2025-09-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0017_topicyoutubevideo_delete_topicmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicSocialEmbed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("html", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_embeds",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
