# Generated by Django 5.2.6 on 2025-09-16 08:40

import re
from urllib.parse import urlparse

from django.db import migrations, models


def populate_tweet_ids(apps, schema_editor):
    TopicTweet = apps.get_model('topics', 'TopicTweet')
    pattern = re.compile(r"/status(?:es)?/(?P<id>\d+)")
    for tweet in TopicTweet.objects.all():
        path = urlparse(tweet.url or '').path or ''
        match = pattern.search(path)
        tweet_id = match.group('id') if match else str(tweet.pk)
        if tweet.tweet_id != tweet_id:
            tweet.tweet_id = tweet_id
            tweet.save(update_fields=['tweet_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0018_topicsocialembed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TopicSocialEmbed",
            new_name="TopicTweet",
        ),
        migrations.AlterModelOptions(
            name="topictweet",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="topictweet",
            name="topic",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="tweets",
                to="topics.topic",
            ),
        ),
        migrations.RemoveField(
            model_name="topictweet",
            name="provider",
        ),
        migrations.AddField(
            model_name="topictweet",
            name="tweet_id",
            field=models.CharField(db_index=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(populate_tweet_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="topictweet",
            constraint=models.UniqueConstraint(
                fields=("topic", "tweet_id"),
                name="unique_topic_tweet",
            ),
        ),
    ]
