# Generated by Django 5.2.6 on 2025-09-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0019_auto_20250916_0840"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "DOC"),
                            ("docx", "DOCX"),
                            ("ppt", "PowerPoint"),
                            ("xls", "Spreadsheet"),
                            ("txt", "Text"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["topic"], name="topics_topi_topic_i_e00806_idx"
                    ),
                    models.Index(
                        fields=["document_type"], name="topics_topi_documen_eeb3ff_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TopicWebpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpages",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webpage",
                "verbose_name_plural": "Webpages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["topic"], name="topics_topi_topic_i_e5a6e5_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="topics_topi_created_a10f6b_idx"
                    ),
                ],
            },
        ),
    ]
