# Generated by Django 5.2.6 on 2025-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0020_topicdocument_topicwebpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
