# Generated by Django 5.2.6 on 2025-10-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0022_topicdatarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdatarequest',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicdatarequest',
            name='saved_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='topics.topicdata'),
        ),
    ]
