# Generated by Django 5.2.7 on 2025-10-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0023_topicdatarequest_saved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicdata",
            name="url",
        ),
        migrations.AddField(
            model_name="topicdata",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicdata",
            name="sources",
            field=models.JSONField(default=list),
        ),
    ]
