# Generated by Django 5.2.7 on 2025-10-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0024_remove_topicdata_url_topicdata_explanation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicModuleLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_key", models.CharField(max_length=50)),
                (
                    "placement",
                    models.CharField(
                        choices=[("primary", "Primary"), ("sidebar", "Sidebar")],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "size_variant",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("compact", "Compact"),
                            ("expanded", "Expanded"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_layouts",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "unique_together": {("topic", "module_key")},
            },
        ),
    ]
