# Generated by Django 5.2.7 on 2025-10-05 15:13

from django.db import migrations


DEFAULT_LAYOUT = [
    ("images", "primary", "expanded"),
    ("recaps", "primary", "default"),
    ("data", "primary", "default"),
    ("data_visualizations", "primary", "default"),
    ("narratives", "primary", "default"),
    ("embeds", "primary", "default"),
    ("relations", "primary", "default"),
    ("related_events", "sidebar", "default"),
    ("timeline", "sidebar", "default"),
    ("documents", "sidebar", "default"),
]


def seed_topic_module_layout(apps, schema_editor):
    Topic = apps.get_model("topics", "Topic")
    TopicModuleLayout = apps.get_model("topics", "TopicModuleLayout")

    for topic in Topic.objects.all():
        for order, (module_key, placement, size_variant) in enumerate(DEFAULT_LAYOUT, start=1):
            TopicModuleLayout.objects.create(
                topic=topic,
                module_key=module_key,
                placement=placement,
                size_variant=size_variant,
                display_order=order,
            )


def unseed_topic_module_layout(apps, schema_editor):
    TopicModuleLayout = apps.get_model("topics", "TopicModuleLayout")
    TopicModuleLayout.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0025_topicmodulelayout"),
    ]

    operations = [
        migrations.RunPython(seed_topic_module_layout, unseed_topic_module_layout),
    ]
