# Generated by Django 5.2.6 on 2025-10-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('topics', '0029_topic_last_published_at_topicdata_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpublisheddatainsight',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublisheddatavisualization',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublisheddocument',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedevent',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedimage',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedrecap',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedrelation',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedtext',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedtweet',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedwebpage',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='topicpublishedyoutubevideo',
            name='publication',
        ),
        migrations.CreateModel(
            name='TopicPublicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=100)),
                ('module_key', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='topics.topicpublication')),
            ],
            options={
                'ordering': ('publication', 'id'),
            },
        ),
        migrations.DeleteModel(
            name='TopicPublishedData',
        ),
        migrations.DeleteModel(
            name='TopicPublishedDataInsight',
        ),
        migrations.DeleteModel(
            name='TopicPublishedDataVisualization',
        ),
        migrations.DeleteModel(
            name='TopicPublishedDocument',
        ),
        migrations.DeleteModel(
            name='TopicPublishedEvent',
        ),
        migrations.DeleteModel(
            name='TopicPublishedImage',
        ),
        migrations.DeleteModel(
            name='TopicPublishedRecap',
        ),
        migrations.DeleteModel(
            name='TopicPublishedRelation',
        ),
        migrations.DeleteModel(
            name='TopicPublishedText',
        ),
        migrations.DeleteModel(
            name='TopicPublishedTweet',
        ),
        migrations.DeleteModel(
            name='TopicPublishedWebpage',
        ),
        migrations.DeleteModel(
            name='TopicPublishedYoutubeVideo',
        ),
        migrations.AddIndex(
            model_name='topicpublicationsnapshot',
            index=models.Index(fields=['publication', 'component_type'], name='topics_topi_publica_4e9d6d_idx'),
        ),
    ]
