# Generated by Django 5.2.7 on 2025-10-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    app_label = "topics"

    dependencies = [
        ("topics", "0031_topicdataanalysisrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicRelatedTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Automatic")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_topic_related_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_related_topic_links",
                        to="topics.topic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_related_topics",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="related_topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_topics",
                through="topics.TopicRelatedTopic",
                to="topics.topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicrelatedtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "related_topic"), name="unique_topic_related_topic"
            ),
        ),
    ]
