# Generated by Django 5.2.7 on 2025-10-21 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    app_label = "topics"

    dependencies = [
        ("topics", "0032_topicrelatedtopic_topic_related_topics_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TopicRelatedTopic",
            new_name="RelatedTopic",
        ),
        migrations.AlterField(
            model_name="topic",
            name="related_topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_topics",
                through="topics.RelatedTopic",
                to="topics.topic",
            ),
        ),
    ]
