# Generated by Django 5.2.7 on 2025-10-24 19:03

from django.db import migrations, models


def set_initial_topic_image_hero(apps, schema_editor):
    TopicImage = apps.get_model("topics", "TopicImage")

    topic_ids = (
        TopicImage.objects
        .filter(topic_id__isnull=False)
        .values_list("topic_id", flat=True)
        .distinct()
    )

    for topic_id in topic_ids:
        hero = (
            TopicImage.objects
            .filter(
                topic_id=topic_id,
                status="finished",
                is_deleted=False,
            )
            .order_by("-created_at")
            .first()
        )
        if not hero:
            continue

        (
            TopicImage.objects
            .filter(topic_id=topic_id, is_hero=True)
            .exclude(pk=hero.pk)
            .update(is_hero=False)
        )
        if not hero.is_hero:
            hero.is_hero = True
            hero.save(update_fields=["is_hero"])


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0033_rename_topicrelatedtopic_relatedtopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicimage",
            name="is_hero",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_initial_topic_image_hero,
            migrations.RunPython.noop,
        ),
    ]
