# Generated by Django 5.2.7 on 2025-10-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0034_topicimage_is_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmodulelayout",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
