# Generated by Django 5.2.1 on 2025-10-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_event_locality_settings'),
        ('entities', '0001_initial'),
        ('topics', '0035_topicmodulelayout_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicentity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topicentity',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='topicentity',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='relatedtopic',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='relatedtopic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='relatedtopic',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='relatedtopic',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='relatedtopic',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='relatedtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
        migrations.CreateModel(
            name='RelatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEntity', to='entities.entity'),
        ),
        migrations.CreateModel(
            name='RelatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.event')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='topics', through='topics.RelatedEvent', to='agenda.event'),
        ),
        migrations.DeleteModel(
            name='TopicEntity',
        ),
        migrations.AddConstraint(
            model_name='relatedentity',
            constraint=models.UniqueConstraint(fields=('topic', 'entity'), name='unique_topic_related_entity'),
        ),
        migrations.AddConstraint(
            model_name='relatedevent',
            constraint=models.UniqueConstraint(fields=('topic', 'event'), name='unique_topic_related_event'),
        ),
    ]
