# Generated by Django 5.2.7 on 2025-10-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0036_remove_topic_contents_remove_topicentity_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="updated_at",
        ),
    ]
