# Generated by Django 5.2.1 on 2024-11-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0037_remove_topic_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedtopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_related_topics",
                to="topics.topic",
            ),
        ),
    ]
