# Generated by Django 5.2.1 on 2025-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0038_alter_relatedtopic_topic_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedentity',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
