# Generated by Django 5.2.6 on 2025-09-20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0039_relatedentity_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopicEntityRelation",
        ),
    ]
