# Generated by Django 5.2.7 on 2025-10-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0040_remove_topicentityrelation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedentity",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_entities",
                to="topics.topic",
            ),
        ),
        migrations.AlterField(
            model_name="relatedevent",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_event_links",
                to="topics.topic",
            ),
        ),
    ]
