# Generated by Django 5.2.7 on 2025-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
        ("topics", "0041_alter_relatedentity_topic_alter_relatedevent_topic"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="relatedentity",
            name="unique_topic_related_entity",
        ),
        migrations.AddConstraint(
            model_name="relatedentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("topic", "entity"),
                name="unique_topic_related_entity",
            ),
        ),
    ]
