# Generated by Django 5.2.1 on 2025-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0031_remove_publication_models'),
        ('topics', '0042_update_relatedentity_unique_constraint'),
    ]

    operations = [
    ]
