# Generated by Django 5.2.1 on 2025-10-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0043_merge_20251028_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topicevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topicevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='topicevent',
            name='topic',
        ),
        migrations.RemoveConstraint(
            model_name='topic',
            name='unique_topic_title_user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='topictitle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='topics.topic'),
        ),
        migrations.DeleteModel(
            name='TopicEvent',
        ),
        migrations.AddConstraint(
            model_name='topictitle',
            constraint=models.UniqueConstraint(fields=('slug', 'topic'), name='unique_topic_title_slug'),
        ),
    ]
