# Generated by Django 5.2.1 on 2025-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0046_remove_topicmodulelayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicdata',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topicdatainsight',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topicdatavisualization',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topicdocument',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='topicimage',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topictext',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topictweet',
            options={'ordering': ('display_order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='topicwebpage',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Webpage', 'verbose_name_plural': 'Webpages'},
        ),
        migrations.AlterModelOptions(
            name='topicyoutubevideo',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.RenameIndex(
            model_name='topicdocument',
            new_name='topics_topi_display_8bcffc_idx',
            old_name='topics_topicdoc_disp_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='topicwebpage',
            new_name='topics_topi_display_6d54df_idx',
            old_name='topics_topicweb_disp_ord_idx',
        ),
    ]
