# Generated by Django 5.2.6 on 2025-12-17 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('normalized_url', models.URLField(max_length=500, unique=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=200)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_published_at', models.DateTimeField(blank=True, null=True)),
                ('lead_image_url', models.URLField(blank=True, max_length=500)),
                ('content_excerpt', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('fetch_error', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-last_fetched_at', '-first_seen_at'),
            },
        ),
        migrations.CreateModel(
            name='TopicReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_suggested', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('content_version_snapshot', models.PositiveIntegerField(default=1)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='references.reference')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reference_links', to='topics.topic')),
            ],
            options={
                'ordering': ('-added_at',),
                'unique_together': {('reference', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='references', through='references.TopicReference', to='topics.topic'),
        ),
    ]
