# Generated by Django 5.2.1 on 2025-06-17 12:54

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_fetch', models.DateTimeField(auto_now=True)),
                ('last_fetch_error', models.CharField(blank=True, max_length=500, null=True)),
                ('consecutive_error_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.content')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rss_content.rsssource')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rssitem_embedding_hnsw', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
