# Generated by Django 5.2.1 on 2025-06-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic_recaps', '0001_initial'),
        ('topics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrecap',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='topics.topic'),
        ),
    ]
