# Generated by Django 5.2.1 on 2025-09-05 03:39

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    run_before = [
        ('agenda', '0001_initial'),
    ]

    dependencies = []

    operations = [
        CreateExtension("vector"),
    ]

