# Generated by Django 5.2.1 on 2025-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
