# Generated by Django 5.2.1 on 2025-08-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_entry_options_entry_previous_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='title',
        ),
    ]
