# Generated by Django 5.2.1 on 2025-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_source_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='domain',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
