# Generated by Django 5.2.1 on 2025-08-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_name_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contents',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Agenda entry', 'verbose_name_plural': 'Agenda entries'},
        ),
        migrations.DeleteModel(
            name='EntryContent',
        ),
    ]
