# Generated by Django 5.2.1 on 2025-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_entry_contents_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('rule', 'Rule')], default='user', max_length=10),
        ),
    ]
