# Generated by Django 5.2.1 on 2025-08-24 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_entry_description_entry_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('title', 'date'), name='unique_entry_title_date'),
        ),
    ]
