# Generated by Django 5.2.1 on 2025-08-24 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_entry_unique_entry_title_date'),
        ('contents', '0003_alter_content_created_at'),
        ('topics', '0009_remove_topicimage_topicimage_embedding_hnsw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Event',
        ),
    ]
