# Generated by Django 5.2.1 on 2025-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_rename_entry_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
