# Generated by Django 5.2.1 on 2025-08-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_event_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
