# Generated by Django 5.2.1 on 2025-08-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='significance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very low'), (2, 'Low'), (3, 'Normal'), (4, 'High'), (5, 'Very high')], null=True),
        ),
    ]
