# Generated by Django 5.2.1 on 2025-08-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_event_significance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='significance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Normal'), (4, 'High'), (5, 'Very high')], default=4),
        ),
    ]
