# Generated by Django 5.2.1 on 2025-08-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_alter_event_significance'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
