# Generated by Django 5.2.1 on 2025-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_locality_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
        migrations.AddField(
            model_name='event',
            name='sources',
            field=models.ManyToManyField(blank=True, to='agenda.source'),
        ),
    ]
