# Generated by Django 5.2.1 on 2025-08-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_source_remove_event_source_event_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
