# Generated by Django 6.0.2 on 2026-02-18 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0002_topicsectionsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTopicConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('newsradar', 'NewsRadar')], db_index=True, max_length=50)),
                ('external_topic_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_connections', to='topics.topic')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('provider', 'external_topic_id'), ('provider', 'topic')},
            },
        ),
    ]
