# Generated by Django 5.2.1 on 2025-10-25 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topicbookmark',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='topicbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='topicbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic_bookmark'),
        ),
    ]
