# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("type", models.CharField(choices=[('images', 'Images'), ('text', 'Text block'), ('data', 'Data block'), ('timeline', 'Timeline'), ('webcontents', 'Web content')], max_length=50)),
                ("prompt", models.TextField(blank=True, help_text="Prompt sent to the LLM for this widget.")),
                ("response_format", models.JSONField(blank=True, default=dict, help_text="Expected response formatting metadata.")),
                ("tools", models.JSONField(blank=True, default=list, help_text="List of tool identifiers made available to the LLM.")),
                ("template", models.TextField(blank=True, help_text="Template used to render the widget's content.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
