# Generated by Django 5.2.7 on 2025-11-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('input_format', models.JSONField(default=list, help_text='List of input field definitions.')),
                ('context_structure', models.JSONField(blank=True, default=dict, help_text='The context parameters to be passed to the template.')),
                ('template', models.TextField(blank=True, help_text="Template used to render the widget's content.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, max_length=150)),
                ('prompt_template', models.TextField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list, help_text='List of tool identifiers made available to the LLM.')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='widgets.widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(blank=True, help_text='Registry type identifier used to resolve execution strategy.', max_length=100)),
                ('prompt_template', models.TextField(blank=True)),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('prompt_text', models.TextField(blank=True)),
                ('extra_instructions', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=150)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('response_schema', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('parsed_response', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.widgetaction')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='topics.topicsection')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
