# Generated by Django 5.2.7 on 2025-11-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widget",
            old_name="prompt",
            new_name="prompt_template",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="type",
        ),
    ]
