# Generated by ChatGPT
from django.db import migrations, models


REMOVED_WIDGET_TYPES = {
    "title",
    "recap",
    "events",
    "related_topics",
    "entities",
}


def migrate_widget_types(apps, schema_editor):
    TopicWidget = apps.get_model("widgets", "TopicWidget")
    TopicWidget.objects.filter(widget_type="cover_image").update(widget_type="images")
    TopicWidget.objects.filter(widget_type__in=("external_links", "documents")).update(
        widget_type="webcontents"
    )
    TopicWidget.objects.filter(widget_type__in=REMOVED_WIDGET_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_remove_topicwidget_placement"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="topicwidget",
            name="widgets_unique_singleton_per_language",
        ),
        migrations.RunPython(migrate_widget_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="topicwidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("images", "Images"),
                    ("text", "Text block"),
                    ("data", "Data block"),
                    ("timeline", "Timeline"),
                    ("webcontents", "Web content"),
                ],
                max_length=50,
            ),
        ),
    ]
