# Generated by Django 5.2.7 on 2025-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_seed_default_widgets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="type",
            field=models.CharField(
                choices=[
                    ("image", "Image block"),
                    ("text", "Text block"),
                    ("data", "Data block"),
                    ("webcontent", "Web content"),
                ],
                max_length=50,
            ),
        ),
    ]
