# Generated by Django 5.2.7 on 2025-11-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0003_widgetapiexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetapiexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("manual", "Manual"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
