# Generated by Django 5.2.7 on 2025-11-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_delete_mcpserver_remove_topicdatainsight_sources_and_more'),
        ('widgets', '0004_alter_widgetapiexecution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={},
        ),
        migrations.RemoveField(
            model_name='widget',
            name='prompt_template',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='input_format',
            field=models.JSONField(default=[{'required': True, 'type': 'text'}], help_text='List of input field definitions.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='response_format',
            field=models.JSONField(blank=True, default=dict, help_text='Response format definition.'),
        ),
        migrations.CreateModel(
            name='WidgetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, max_length=150)),
                ('prompt_template', models.TextField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list, help_text='List of tool identifiers made available to the LLM.')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.widgetaction')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='topics.topicsection')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.DeleteModel(
            name='WidgetAPIExecution',
        ),
    ]
