# Generated by Django 5.2.7 on 2025-11-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_alter_widget_options_remove_widget_prompt_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetaction',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='widgets.widget'),
        ),
    ]
