# Generated by Django 5.2.7 on 2025-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_alter_widgetaction_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='response_format',
        ),
        migrations.AddField(
            model_name='widget',
            name='context_structure',
            field=models.JSONField(blank=True, default=dict, help_text='The context parameters to be passed to the template.'),
        ),
    ]
