# Generated by Django 5.2.7 on 2025-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0007_remove_widget_response_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetactionexecution",
            name="extra_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="model_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="parsed_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="prompt_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="prompt_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="prompt_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="raw_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="response_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="widgetactionexecution",
            name="widget_type",
            field=models.CharField(
                blank=True,
                help_text="Registry type identifier used to resolve execution strategy.",
                max_length=100,
            ),
        ),
    ]
