# Generated by Django 5.2.1 on 2025-09-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentevent',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='contentevent',
            name='rank',
        ),
    ]
