# Generated by Django 5.2.1 on 2025-08-23 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_entry_contents_alter_entry_options_and_more'),
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('user', 'User'), ('rule', 'Rule')], default='agent', max_length=10)),
                ('relevance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('pinned', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.entry')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='entries',
            field=models.ManyToManyField(related_name='contents', through='contents.ContentEntry', to='agenda.entry'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['entry'], name='contents_co_entry_i_168c24_idx'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['content'], name='contents_co_content_8b4d40_idx'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['-relevance'], name='contents_co_relevan_8463bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contententry',
            unique_together={('content', 'entry', 'source')},
        ),
    ]
