# Generated by Django 5.2.1 on 2025-08-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_rename_entry_event'),
        ('contents', '0003_alter_content_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentEntry',
            new_name='ContentEvent',
        ),
        migrations.RemoveIndex(
            model_name='contentevent',
            name='contents_co_entry_i_168c24_idx',
        ),
        migrations.RenameField(
            model_name='contentevent',
            old_name='entry',
            new_name='event',
        ),
        migrations.RenameIndex(
            model_name='contentevent',
            new_name='contents_co_content_70a566_idx',
            old_name='contents_co_content_8b4d40_idx',
        ),
        migrations.RenameIndex(
            model_name='contentevent',
            new_name='contents_co_relevan_114cff_idx',
            old_name='contents_co_relevan_8463bc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contentevent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='content',
            name='entries',
        ),
        migrations.AddField(
            model_name='content',
            name='events',
            field=models.ManyToManyField(related_name='contents', through='contents.ContentEvent', to='agenda.event'),
        ),
        migrations.AddIndex(
            model_name='contentevent',
            index=models.Index(fields=['event'], name='contents_co_event_i_a3f916_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentevent',
            constraint=models.UniqueConstraint(fields=('content', 'event', 'source'), name='unique_content_event__source'),
        ),
    ]
