# Generated by Django 5.2.1 on 2025-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_rename_contententry_contentevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCPServer',
        ),
    ]
