# Generated by Django 5.2.1 on 2025-06-17 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('default_language', models.CharField(default='tr', max_length=5)),
                ('channel_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('uploads_playlist_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('channel_last_update', models.DateTimeField(blank=True, null=True)),
                ('channel_next_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_short', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_content.channel')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transcript_data', models.JSONField(blank=True, default=dict)),
                ('language_code', models.CharField(max_length=10)),
                ('is_generated', models.BooleanField(default=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube_content.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField(help_text='Start time in seconds')),
                ('raw_text', models.TextField(help_text='The raw text content of the chunk')),
                ('revised_text', models.TextField(blank=True, help_text='The revised text content of the chunk', null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='youtube_content.videotranscript')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='videotranscript',
            constraint=models.UniqueConstraint(fields=('video', 'language_code'), name='unique_video_language'),
        ),
    ]
